version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "mokydb"
      POSTGRES_USER: "mokyuser"
      POSTGRES_PASSWORD: "pwd4moky"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nats-streaming:
    command:
      - "--cid"
      - test
      - "--dir"
      - store
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8223:8223"